### ISSUE TITLE
Problem of returning to normal mode with coc-omni

### ISSUE THREAD

**Issue by maamo888** [neoclide/coc-sources#11]
## Describe

Hi,

There is a template engine called `blade` in PHP's `Laravel` framework.

https://laravel.com/docs/5.8/blade

When `vim-blade` plugin is used, the filetype becomes `blade`.

When using `coc-omni` with a `blade`, I confirmed the problem of returning to normal mode during input.

## Related plugin

```vimrc
Plug 'neoclide/coc.nvim', { 'do': './install.sh nightly' }
Plug 'jwalton512/vim-blade', { 'for': ['blade'] }
```

## versions

```
vim version: NVIM v0.4.0-1077-gde2e51439
node version: v10.16.0
coc.nvim version: 0.0.71-9740746768
term: iTerm.app
platform: darwin
```

## coc-omni related coc-settings.json

```json
  "coc.source.omni.enable": true,
  "coc.source.omni.filetypes": ["blade"],
  "coc.source.omni.triggerCharacters": [" ", "<", "/"],
```

## Gif

![coc-omni-issue-190625](https://user-images.githubusercontent.com/14961986/60105106-b0993100-979d-11e9-8177-cd509b295ebd.gif)

**Comment by chemzqm** [comment]
Should be problem of your `&omnifunc`, we can do nothing for it.
My advice is avoid omnifunc as much as possible.

**Comment by maamo888** [comment]
I'm sorry. I will talk about a simpler example.

`blade`'s omnifunc is `htmlcomplete#CompleteTags`.

It also occurs with regular html files.

I always use `coc-html`, but uninstalling `coc-html` and editing html files with `coc-omni` will cause similar symptoms.

**coc-omni related coc-settings.json**

```
  "coc.source.omni.enable": true,
  "coc.source.omni.filetypes": ["html"],
  "coc.source.omni.triggerCharacters": [" ", "<", "/"],
```

**Comment by chemzqm** [comment]
omnifunc like `htmlcomplete#CompleteTags` can't work with auto trigger completion, use `<C-x><C-o>` instead.

**Comment by maamo888** [comment]
In `coc.nvim + coc-omni`, omnifunc understood about deprecation.

As a precaution, I will tell you that `ncm2` and `asyncomplete.vim + asyncomplete-omni.vim` are working without problems.

**Gif: asyncompelte + asyncomplete-omni**
 
![coc-omni-issue-asyncomplete-omni](https://user-images.githubusercontent.com/14961986/60144663-41075e00-97fe-11e9-9729-2a8353c9feea.gif)

Thanks.

**Comment by chemzqm** [comment]
It's possible to fix this issue by using timer or something else, but I will make any effort for it, because omnifunc sucks.

**Comment by maamo888** [comment]
I do not want to use `omnifunc`, but I can not use it if I try to use `blade` or `htmldjango` with `coc-html`.

**coc-html related coc-settings.json**

```json
  "html.filetypes": ["html", "handlebars", "blade", "htmldjango"],
```

**Comment by chemzqm** [comment]
You can, checkout `:h g:coc_filetype_map`

**Comment by maamo888** [comment]
Wow, I could use `blade` with `coc-html`.

This is already comfortable!!!
