### ISSUE TITLE
Buggy cursor behavior on coc-omni

### ISSUE THREAD

**Issue by wookayin** [neoclide/coc-sources#12]
When we type very fast (e.g. holding one key), the cursor gets to a wrong position.

Please see the screenshot:

![Video](https://user-images.githubusercontent.com/1009873/60631254-76d6b480-9db3-11e9-8fc7-909f8d7e13c3.gif)

I suspect this line is the cause: https://github.com/neoclide/coc-sources/blob/698b9c5/packages/omni/index.js#L46

**Comment by chemzqm** [comment]
Avoid coc-omni or avoid typing fast.

**Comment by wookayin** [comment]
Thanks for the fast fix. Well, I was not typing really fast -- even with just **a normal typing speed** it behaves wrong.

With 1.2.4, I still have the problem unfixed. How did you test it?

**Comment by chemzqm** [comment]
I can't help then, you can use `<C-x><C-o>` instead of this extension.

**Comment by wookayin** [comment]
I see. can you please let me know what is blocking? Why do we need to set cursor position? -- maybe because invoking omnifunc inside vim does not work asynchronously?

**Comment by chemzqm** [comment]
You can look at the source code, it have to trigger two request to vim.
