### ISSUE TITLE
Unable to get Terraform completions

### ISSUE THREAD

**Issue by svanharmelen** [neoclide/coc-sources#14]
I am trying to get completions from [vim-terraform-completion](https://github.com/juliosueiras/vim-terraform-completion) working with the `omni` source, but I cannot get it to work.

It seems related to the trigger pattern, so I tried to create a small [`coc-terraform`](https://github.com/svanharmelen/coc-terraform) extension simular to what you created for `coc-vimtex`. Yet it will never autoload (I have to enable the extention using `:CocList` > `extentions`) and then it will still not trigger completions 😞 

If I try it using the `deoplete` example that is in the [`README.md`](https://github.com/juliosueiras/vim-terraform-completion#deoplete-config) of `vim-terraform-completion` repo, the completions work as expected so the completions themselves seem to work as expected.

Could you maybe have a quick look and tell me what I'm doing wrong? If we get it working that it would also be nice to move (or just create) the plugin under your Github org.

Thanks!

**Comment by chemzqm** [comment]
I don't have time for it, you can debug it in Chrome https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by svanharmelen** [comment]
😞

**Comment by svanharmelen** [comment]
I fully understand and appreciate that you don't have time to help debug/fix everything, but at least some pointers would be really, really helpful for me to know where to look at.

As you can see by the extension I tried to create, I did invest some time to try and figure things out myself before creating this issue. But as I'm stuck right now and as I'm not a typescript/javascript developer, the page you linked to isn't helpful if I don't know what to look for or what to debug.

To recap, I have two issues:

1. The plugin doesn't enable automatically when opening a file with the registered extension
2. It seems the pattern used as the trigger isn't working as expected

If you could only give a few pointers (examples, links to docs or just links to the relevant source code that is responsible for these parts) that would at least give me a point were I could start writing some `console.error` lines in order to try and understand how it should work and what goes wrong in my case.

Hope you can find a minute to unblock me. Thanks...

**Comment by chemzqm** [comment]
> The plugin doesn't enable automatically when opening a file with the registered extension.

It's controlled by `activationEvents` in package.json.

> It seems the pattern used as the trigger isn't working as expected

It's problem of your `pattern`, checkout RegExp docs of javascript and test it out in console or your browser or node REPL.

**Comment by svanharmelen** [comment]
Thanks for the pointers! I'm going to have another look 👍

**Comment by clog-rocks** [comment]
@svanharmelen Did you manage to get it to work?

**Comment by svanharmelen** [comment]
No, I didn't follow up on it and now use https://github.com/juliosueiras/terraform-lsp which works reasonably...

**Comment by clog-rocks** [comment]
Yes, found that last night too. Thanks!
