### ISSUE TITLE
Emoji completion leaves colon

### ISSUE THREAD

**Issue by AtomToast** [neoclide/coc-sources#15]
When using the emoji completion the colon that triggers it is left over after completion.
Leading to it always looking like :🦄
This might be because it doesn't complete it like discord to just the emote name eg :unicorn: but the actual unicode character but is there a way of creating an autoremove for the leading colon upon completion?

**Comment by chemzqm** [comment]
You need confirm completion, please read wiki of coc.nvim

**Comment by WhyNotHugo** [comment]
I had the same issue and added this to my `init.vim`, and effectively, pressing enter removes the colons before the emojis.

```vim
if exists('*complete_info')
  inoremap <expr> <cr> complete_info()["selected"] != "-1" ? "\<C-y>" : "\<C-g>u\<CR>"
endif
```

However, for code completions I _do not_ have to press enter and it just works as expected.

Is there any way to work around this for emojis? It feels very unnatural to have to press enter after typing an emoji each time.
