### ISSUE TITLE
Snippets from user-defined directories not shown in list (ultisnips)

### ISSUE THREAD

**Issue by cristobaltapia** [neoclide/coc-sources#16]
Hi,
thanks for your work in all these plugins! I am really enjoying using coc.nvim.

I know that there is a specialized plugin to support ultisnips format ([coc-snippets](https://github.com/neoclide/coc-snippets)), however, there are some snipets that don't work correctly.
I have some user-defined snippet directories, which I configured as:

```vim
let g:UltiSnipsSnippetDirectories=[
            \'UltiSnips',
            \$HOME.'/.vim/plugged/MySnippets/Ultisnips',
            \$HOME.'/Templates/ultisnips-templates'
            \]
```

The snippets trigger correctly, but there is no completion pop-up showing the alternatives. 

In the coc-configuration I added:
```json
    ...
    "coc.source.ultisnips.enable": true,
    "coc.source.ultisnips.filetypes": ["py"],
    ...
```

What might be the problem?

**Comment by chemzqm** [comment]
It's documented in readme, coc-snippets doesn't use any ultisnip configuration, you have to add it in settings.json

**Comment by cristobaltapia** [comment]
I know that. However, I thought that using `coc-ultisnips` (not `coc-snippets`) was the way to go if I wanted to maintain 100% compatibility with ultisnips.
What is `coc-ultisnips` for then?

**Comment by cristobaltapia** [comment]
Forget it. Now it is working :)
