### ISSUE TITLE
coc-emoji: Extra character inserted when using a non-ASCII trigger char

### ISSUE THREAD

**Issue by pschmitt** [neoclide/coc-sources#19]
I'm trying to use `·` as a trigger char. 
When I select an emoji after having pressed this char the inserted text is prefixed with `�`. 
So instead of inserting `🆗` for example it's  `�🆗`. 
This behavior can be observed with the characters `…` and `’` as well. With others (`µ`, `ø`) the completion never triggers (no emoji selector is shown).

Example config:
```
{
  "coc.source.emoji.filetypes": null,
  "coc.source.emoji.triggerCharacters": [":", "…", "·", "ø", "µ"]
}
```

**Comment by chemzqm** [comment]
It's just not supported.

**Comment by rogeruiz** [comment]
When I attempt to use the default trigger of `:`, `coc-emoji` does not remove the trigger character when adding the emoji. Is there a way to achieve this functionality?

**Comment by chemzqm** [comment]
You have to confirm completion，check wiki of coc.nvim.

**Comment by disanman** [comment]
Hello! 
I am having a similar issue that one reported here, but when using a [custom source](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source). In my case, the `triggerCharacter` remains even after confirming the completion... I tried confirming the completion using:
- `<C-y>` in insert mode after selecting the option to complete, and 
- `inoremap <expr><C-y> coc#_select_confirm()` 

but the `triggerCharacter` always remain even after the completion is confirmed.  
I tried the `coc-emoji` plugin and the `triggerCharacter` `:` is in fact removed when using `<C-y>` but that's not the case for custom sources... @chemzqm, do you maybe any hint to solve this issue?

**Comment by chemzqm** [comment]
@disanman seems you don't have correct `startcol` returned from source.
