### ISSUE TITLE
coc-code - Where has the repository gone?

### ISSUE THREAD

**Issue by tobydeh** [neoclide/coc-sources#2]
coc-gocode has stopped working, has the repository been removed?

**Comment by chemzqm** [comment]
It's coc-gocode https://www.npmjs.com/package/coc-gocode

**Comment by tobydeh** [comment]
The npm link points to a dead URL: https://github.com/neoclide/coc-gocode

**Comment by chemzqm** [comment]
It's monorepo now, so link by url doesn't work, remove the link and use `CocInstall coc-gocode` to install it.

**Comment by tobydeh** [comment]
Unfortunately it's still not working. It was working fine until recently? 

This is the output of CocInfo:

```
## versions

vim version: NVIM v0.3.4
node version: v8.9.0
coc.nvim version: 0.0.57
term: iTerm.app
platform: darwin

## Error messages
```

**Comment by tobydeh** [comment]
Deleted everything and re installed, now seems to be working. Thank you.
