### ISSUE TITLE
coc-sources: add a configuration to restrict completion to comments

### ISSUE THREAD

**Issue by nicolnt** [neoclide/coc-sources#21]
Hey,
I am opening an issue to make a new configuration suggestion. I was looking forward to get coc-word completion only when typing a comment. 
I don't know if it can be extended to larger possibilities.
Thanks :smiley:

**Comment by chemzqm** [comment]
There is `disableSyntaxes` configuration for sources https://github.com/neoclide/coc-sources/blob/master/Readme.md#configure

**Comment by nicolnt** [comment]
Oh so sorry I've missed the general coc-source configs! You guys rock 🔥

**Comment by nicolnt** [comment]
I don't quite get how I am supposed to restrict to comments as `disableSyntaxes` seems to be used to disable a specific kind of text, where I am trying to do the opposite.

I tried adding this setting to my `coc-settings.json` and restart NeoVim but `coc-word` is still enabled everywhere (inside or outside comments and strings).
`"coc.source.word.disableSyntaxes": [ "string", "comment" ]`

I've tried with this very simple `coc-settings.json` and my other configurations work fine.
```javascript
{
  "coc.source.word.disableSyntaxes": [ "string", "comment" ]
}
```

**Comment by nomasprime** [comment]
I'm trying to do the same thing. Looking for the opposite of `disableSyntaxes`: just want coc-dictionary for comments and strings, nothing else.

Trying to find a complete list of syntaxes to remove comments and strings, achieving the same thing.

**Comment by nomasprime** [comment]
@chemzqm is there an `enableSyntaxes` option or a complete list of syntaxes somewhere?

**Comment by chemzqm** [comment]
Seems reasonable.
