### ISSUE TITLE
coc-syntax: Illegal variable name

### ISSUE THREAD

**Issue by chinnkarahoi** [neoclide/coc-sources#23]
Error detected while processing function syntaxcomplete#Complete[47]..OmniSyntaxList:
E461: Illegal variable name: syntax_group_include_yaml_docker-compose

triggered by omni completion in docker-compose.yml

**Comment by chemzqm** [comment]
It's not from coc.nvim.

**Comment by dllvhaobo** [comment]
how to resolve this issue ？

**Comment by dllvhaobo** [comment]
This is my error log, it's omnifunc issue?  Is there any detail info to resolve this issue?

```bash
[completion-complete] - Complete error: syntax Error: request error on nvim_call_function - Vim(let):E461: Illegal variable name: syntax_group_include_yaml_docker-compose
```
