### ISSUE TITLE
coc-emoji for commit msgs

### ISSUE THREAD

**Issue by balamurali27** [neoclide/coc-sources#26]
Is it possible to have coc-emoji enabled only for when writing git commit messages?  You always edit COMMIT_EDITMSG when you edit commit messages. I didn't see anything in the readme other than specifying filetypes

**Comment by chemzqm** [comment]
Use `  "coc.source.emoji.filetypes": ["gitcommit"],`

**Comment by balamurali27** [comment]
Thanks man! Is there a documentation somewhere for all the file types like this that I missed?

**Comment by chemzqm** [comment]
There is a `configuration` action with `:CocList extensions` which jump to `contributes` field in package.json.

**Comment by balamurali27** [comment]
There's nothing there? I was asking if there were a list of the more filetypes like `gitcommit`, `markdown` ..etc

**Comment by chemzqm** [comment]
Use `:echo &filetype` to get filetype of current buffer.

**Comment by balamurali27** [comment]
ooh, that's really useful. Thanks!
