### ISSUE TITLE
use french dictionary

### ISSUE THREAD

**Issue by grimgort** [neoclide/coc-sources#28]
Hello,

I would like to use a French dictionary. The default one of omni complete of vim is fine, but coc-omni doesn't add anything despite the "set complete+=kspell" option in my vimrc

**Comment by chemzqm** [comment]
`coc-omni` use your `&omnifunc` option for completion which is not affected by `complete` option. Read `:h 'complete'` of how to use vim's keywords completion or create completion source yourself https://medium.com/@chemzqm/create-coc-nvim-extension-to-improve-vim-experience-4461df269173
