### ISSUE TITLE
Emoji Source Doesn't Trigger

### ISSUE THREAD

**Issue by atomdmac** [neoclide/coc-sources#3]
Other completion sources seem to be working but for some reason, typing the `:` doesn't trigger completions for the `coc-emoji` source.  I modified the `fileTypes` and `disabledSyntaxes` values in `coc-settings.json` to ensure that completion could be triggered for any file type in any context but it still doesn't work.

## init.vim
```
call plug#begin()
Plug 'neoclide/coc.nvim', {'tag': '*', 'do': { -> coc#util#install() }}
call plug#end()
filetype plugin on
```
## coc-settings.json
```
{
  "coc.source.emoji.enable": true,
  "coc.source.emoji.filetypes": [],
  "coc.source.emoji.disableSyntaxes": []
}
```

**Comment by chemzqm** [comment]
`"coc.source.emoji.filetypes"` the filetypes is empty, you can change it to `null` for all filetypes.

**Comment by atomdmac** [comment]
Thanks, @chemzqm ! That fixed it.  It's a bit confusing when editing `coc-sources.json` since the schema expects an array and a warning is shown (`Incorrect type. Expected "array"`)  However, it _does_ seem to work as expected.

**Comment by chemzqm** [comment]
I've fixed the schema.

**Comment by Sammyalhashe** [comment]
I have the same config as @atomdmac and I can't trigger any completion. I'm slightly confused on how to use it too. Is it `:smile` or `smile:`?

**Comment by atomdmac** [comment]
@Sammyalhashe `:smile` (with the colon first) should trigger it.  It's possible that emoji completion isn't enabled for the file type that you're editing.  You might try setting `"coc.source.emoji.filetypes": null` in your `coc-settings.json` via the `:CocConfig` command.  This enables emoji completion for all file types but you could use an array to indicate specific types instead.
