### ISSUE TITLE
coc-dictionary does not use by default the vim dictionary (spell option)

### ISSUE THREAD

**Issue by grimgort** [neoclide/coc-sources#30]
hello,
when typing 'h dictionary' it is marked that this variable is set if 'set spell' is used. Would it be possible to use the default vim dictionary, set with the 'set spell' vim option ?

vim doc : 
	When this option is empty or an entry "spell" is present, and spell
	checking is enabled, words in the word lists for the currently active
	'spelllang' are used. See |spell|

thanks a lot

**Comment by chemzqm** [comment]
Checkout `:echo &dictionary` which is used by `coc-dictionary`

**Comment by nomasprime** [comment]
`:echo &dictionary` doesn't seem to do anything. Not sure what coc-dictionary is supposed to do?

What's the best way to add completions from `kspell`?

**Comment by nomasprime** [comment]
OK, looks like `dictionary` isn't set by default, that's why nothing happens.

I had to set manually with `set dictionary=/usr/share/dict/words`.
