### ISSUE TITLE
coc-dictionary breaking coc-lbdbq

### ISSUE THREAD

**Issue by sQVe** [neoclide/coc-sources#4]
:pray:

I'm unsure why but as soon as I install `coc-dictionary` `coc-lbdbq` breaks. Looking at the source code it seems like `coc-lbdbq` is using a newer API.

I'd love some help in finding the issue.

**Comment by sQVe** [comment]
Cross referencing `coc-lbdbq` issue: https://github.com/zidhuss/coc-lbdbq/issues/1

**Comment by chemzqm** [comment]
Can't reproduce, please provide detail information.

**Comment by sQVe** [comment]
I'm using `coc.nvim` built from https://github.com/neoclide/coc.nvim/commit/d3093650393631764765dc53bb9a582a5b38e8ee.

I'm seeing the issue with the following extension `package.json`:

```json
{
  "dependencies": {
    "coc-dictionary": "^1.2.2",
    "coc-lbdbq": "^0.1.0"
  }
}
```

This is what it look like with only `coc-lbdbq` installed:
![working](https://user-images.githubusercontent.com/2284724/57433030-b5c70e80-7237-11e9-9b50-dced9fd21062.gif)

This is what it look like with both `coc-lbdbq` and `coc-dictionary` installed:
![failing](https://user-images.githubusercontent.com/2284724/57433035-b8c1ff00-7237-11e9-8774-d064ab136173.gif)

Give me a ping if you need any more information.

**Comment by sQVe** [comment]
@chemzqm This might actually be a `priority` issue. `coc-lbdbq` sets `priority` to `99` here: https://github.com/zidhuss/coc-lbdbq/blob/master/src/index.ts#L28.

Setting `"coc.source.dictionary.priority": 98` does not work though.

**Comment by chemzqm** [comment]
You can use `suggest.lowPrioritySourceLimit` to limit results form dictionary.

**Comment by sQVe** [comment]
@chemzqm `suggest.lowPrioritySourceLimit` lowers the amount of dictionary suggestions. The `lbdbq` source is still not shown as expected.

**Comment by chemzqm** [comment]
Checkout debug log https://github.com/neoclide/coc.nvim/wiki/Debug-coc.nvim

**Comment by sQVe** [comment]
@chemzqm Works as expected with https://github.com/neoclide/coc.nvim/commit/8668f301e439dd6349a18d83b6b6cd95687317aa
