### ISSUE TITLE
Emoji leaves trigger character

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc-sources#40]
When I type the trigger character `:`, and then I select an emoji, the `:` remains alongside the emoji. Example: `:😄`

Is there a way to prevent this, and remove the trigger character automatically?

**Comment by chemzqm** [comment]
You have to confirm completion, default keymap is `<C-y>`

**Comment by npearson72** [comment]
Is there a way to change it because it conflicts with my Ultisnips settings:

```
let g:UltiSnipsExpandTrigger='<c-y>'

inoremap <silent><expr><c-j> pumvisible() ? "\<c-y><cr><c-r>=UltiSnips#ExpandSnippet()<cr>" : "\<c-j>"
```

**Comment by npearson72** [comment]
Or I guess what I'm looking for, is to understand how to use the same mapping to expand both ultisnips and emoji. Possilbe?

**Comment by chemzqm** [comment]
Like:
```
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

**Comment by npearson72** [comment]
That works! Thank you!
