### ISSUE TITLE
coc-sources does not use spellchecker dictionary

### ISSUE THREAD

**Issue by l-mb** [neoclide/coc-sources#48]
Thanks for making coc-sources available!

I did see issue 30, but the resolution of pointing `dictonary` at a specific file does, alas, not work for me. (Using neovim/vim both.)

The vim built-in checker uses a dictionary format that `dictionary` can't consume. For example, if you do `:setlocal spell spelllang=de`, that will likely download a UTF-8 dictionary file as `~/.vim/spell/de.utf-8.spl` (which is a binary file).

Instead, `help complete` shows that these spellchecking suggestions are treated special via the `set complete+=kspell` option. Which works (the regular insert mode completion of vim (see `ins-completion`)), but obviously not via the same keybindings/UX we love!

I wonder if coc-sources could be extended to access that source as well? Unfortunately I don't know how :-/

Thanks!

**Comment by chemzqm** [comment]
`complete` only affects vim's keywords completion, not coc.nvim.
