### ISSUE TITLE
How to enable case insensitive for tag completion?

### ISSUE THREAD

**Issue by zoumi** [neoclide/coc-sources#53]
I have ```set smartcase``` in my vimrc. 
But it seems that coc-tag doesn't follow this? coc-tag requires the first char to be case sensitive?

**Comment by chemzqm** [comment]
It is smart case but first character must match by design https://github.com/neoclide/coc-sources/blob/master/packages/tag/index.js#L84, you can write your own source which should be easy.

**Comment by zoumi** [comment]
Thank you!
```javascript
         if (input[0].toUpperCase() == input[0])
          {
              if (word[0] !== input[0]) continue
          }
```
