### ISSUE TITLE
coc-gocode does not work

### ISSUE THREAD

**Issue by mnrce** [neoclide/coc-sources#6]
I just installed coc.nvim and coc-gocode on nvim 0.3.5 and nvim 0.4.
When I type `fmt.` nothing happen.

I'm using go 1.12.4 and gocode installed by vim-go.

**Comment by chemzqm** [comment]
Make your your `gocode` command can work in your terminal.

**Comment by mnrce** [comment]
I have $GOPATH/bin in my $PATH so I can run gocode:
![image](https://user-images.githubusercontent.com/13317164/57578116-8a028d80-74b0-11e9-9e9e-099c8aaf6faf.png)

**Comment by chemzqm** [comment]
Make sure `spawn('gocode', ['-f=vim', 'autocomplete', filepath, `c${offset}`])` can work

**Comment by chemzqm** [comment]
You have to use https://github.com/mdempsky/gocode instead of https://github.com/nsf/gocode for newer go version.

**Comment by mnrce** [comment]
yeah, my gocode is from https://github.com/mdempsky/gocode

>  Make sure spawn('gocode', ['-f=vim', 'autocomplete', filepath, c${offset}]) can work
How do I test this?

**Comment by chemzqm** [comment]
Fixed now.
