### ISSUE TITLE
How to disable/enable/toggle a source by CocCommand?

### ISSUE THREAD

**Issue by Freed-Wu** [neoclide/coc-sources#65]
Like <https://github.com/tonyfettes/coc-rime>'s `rime.enable/disable/toggle`

If so, I can `inoremap <C-^> <C-O>:<C-U>CocCommand rime.toggle | CocCommand source.toggle word<CR>` to toggle IME (use rime to insert chinese and word to insert english)

**Comment by chemzqm** [comment]
Use `CocAction('toggleSource')`
