### ISSUE TITLE
[bug] `coc-syntax` doesn't work with `coc.nvim` of branch release

### ISSUE THREAD

**Issue by Lyanyv** [neoclide/coc-sources#73]
But it works with `coc.nvim` of tag `v0.0.81`.

I open an empty buffer and `set ft=vim`.
The output of vim command:
``` vim
:echo syntaxcomplete#OmniSyntaxList()
```
![Snipaste_2023-06-19_18-11-40](https://github.com/neoclide/coc-sources/assets/33587629/10f5c100-d13b-4b6b-8a6c-a1d28047ee93)

It seems that Vim can get syntax keywords.

doesn't work with branch release:
![Snipaste_2023-06-19_18-11-17](https://github.com/neoclide/coc-sources/assets/33587629/d5ee22dc-f158-4b0b-8ee1-014e8bbb71fe)

but it works with an older coc.nvim:

![Snipaste_2023-06-19_18-03-34](https://github.com/neoclide/coc-sources/assets/33587629/cee5ac15-afab-4a80-88bc-3ce60bde4783)

Is it a bug related to `coc-syntax` or `coc.nvim`? Could anyone please help?

**Comment by fannheyward** [comment]
Reproduced, debugging on this.

**Comment by fannheyward** [comment]
Problem:

coc-syntax didn't define default value for `coc.source.syntax.filetypes`, before commit https://github.com/neoclide/coc.nvim/commit/a3d271d8b8e077b9c30a45e8a639647d273d3925 , coc uses `null` as default, after this, the value is `[]` in default, and this will make coc ignore syntax source.

Workaround:

add `"coc.source.syntax.filetypes": null` to your `coc-settings.json` for all filetypes, or `"coc.source.syntax.filetypes": ["vim"]` for special filetype.
