### ISSUE TITLE
Add option to show file path in tag autocomplete

### ISSUE THREAD

**Issue by kristijanhusak** [neoclide/coc-sources#9]
Hi,

it would be great if we could optionally enable showing tag file path in a similar way snippets and typescript docblocks are shown in a floating window.

![screenshot](https://i.imgur.com/plxKfeW.png) 

Additionally, it would be great to allow configuring file path format in a vim style fashion.

So for example, by default it is shown as `%:p`, but if someone wants only a file name, they can change it to `%:t` to show only file name.

This will help in situations where same prop/function/method exists in several places, so you can know where it comes from.

**Comment by chemzqm** [comment]
I don't think it's useful at all, but PR welcome.

**Comment by kristijanhusak** [comment]
Here's PR https://github.com/neoclide/coc-sources/issues/10
